mekomsolutions/ozone-haiti

.github/workflows/check-deps.yml, .github/workflows/ci.yml, .gitignore, pom.xml
As part of setting up the HSC dev server, we need to set up the GA pipelines for this project https://mekomsolutions.atlassian.net/browse/HSC-260
=> HSC-260: Add GA CI pipelines

.ocd3.yml
Adds .ocd3.yml to allow the OCD3 notification to be processed.
=> HSC-260: Add .ocd3.yml file

configs/openmrs/properties/erp.properties, pom.xml, scripts/docker-compose-files.txt, scripts/docker-compose-override.yml
Ticket: https://mekomsolutions.atlassian.net/browse/HSC-319
=> HSC-319: Added OpenMRS module ERP.

configs/openmrs/initializer_config/concepts/anthropometric.csv
Ticket: https://mekomsolutions.atlassian.net/browse/HSC-288
=> HSC-288: Fixed Weight and Height UUIDs

configs/openmrs/initializer_config/encountertypes/encountertypes.csv
Ticket: https://mekomsolutions.atlassian.net/browse/HSC-290
=> HSC-290: Use O3's default Orders encounter type UUID.

configs/openmrs/frontend_assembly/spa-assemble-config.json
https://mekomsolutions.atlassian.net/browse/HSC-306
=> feat: Add esm-patient-billing-status-app to the assemble config

configs/openmrs/initializer_config/ampathforms/ipd_admission_request.json
Ticket: https://mekomsolutions.atlassian.net/browse/HSC-356
[Screencast from 08-01-25 11:01:51.webm](https://github.com/user-attachments/assets/7239290b-29af-4d21-a80c-d9e225a8b3c5)
=> HSC-356: Add Ward Admission Form

configs/openmrs/frontend_assembly/spa-assemble-config.json, configs/openmrs/initializer_config/ordertypes/order_types.csv
Link to the ticket: https://mekomsolutions.atlassian.net/browse/HSC-334
=> (feat) HSC-334: Add medical supply order app to Ozone Haiti

README.md
Ticket: https://mekomsolutions.atlassian.net/browse/OZ-340
This PR updates the README to match the Ozone's rebranding.
=> OZ-340: README as per Ozone's rebranding.

configs/openmrs/initializer_config/concepts/triage.csv
https://mekomsolutions.atlassian.net/browse/HSC-369
Reword the triage concept for better display on the active visit page.
=> HSC-369: Reword Triage Level concept

configs/openmrs/initializer_config/ordertypes/order_types.csv
https://mekomsolutions.atlassian.net/browse/HSC-333
=> HSC-333: Add display values to order types

configs/openmrs/initializer_config/globalproperties/i18n.xml
Ticket: https://mekomsolutions.atlassian.net/browse/HSC-409
=> HSC-409: Set default locale and allowed locales to French

pom.xml
The add Odoo auth_providers to allow for enabling of SSO in Odoo
=> HSC-350: Include Odoo `auth_providers` initializer config

configs/openmrs/frontend_assembly/spa-assemble-config.json, pom.xml
Replicating changes of adding emrapi and bed management module from [this](https://github.com/openmrs/openmrs-distro-referenceapplication/commit/f36e35bd723a80efa2f8d5636e192966cfbd0a72#diff-45f44f9ad29527e45d3c613948ecd1043208780be8a7c864f2a2b8011554ab4a) and [this](https://github.com/openmrs/openmrs-distro-referenceapplication/commit/85b947af55fad9f28139393def8628a450ad4a05) commit from distro ref-app
=> (feat) Add emrapi, bed-management modules to OZ Haiti

configs/openmrs/frontend_assembly/spa-assemble-config.json
https://mekomsolutions.atlassian.net/browse/HSC-420
=> HSC-420: Override ESMs to use latest O3

configs/odoo/initializer_config/units_of_measure/product.uom.csv
JIRA: https://mekomsolutions.atlassian.net/browse/HSC-422
=> Add medical supply product UOMs

configs/openmrs/frontend_assembly/spa-assemble-config.json
Ticket: https://mekomsolutions.atlassian.net/browse/HSC-425
=> HSC-425: Set HSC specific ESMs to fixed versions

pom.xml
PR: https://mekomsolutions.atlassian.net/browse/HSC-432
=> Exclude openmrs CIELImmunizationContent file

configs/openmrs/initializer_config/dispositions/dispositionConfig.json
Set a dispostionConfig.json file to configure ADMIT, TRANSFER, DISCHARGE actions.
https://mekomsolutions.atlassian.net/browse/HSC-356
=> HSC-356: Set the dispositionConfig.json

README.md
Ticket: https://mekomsolutions.atlassian.net/browse/HSC-401
=> HSC-401: Add release notes for version 1.0.0

configs/openmrs/initializer_config/ordertypes/order_types.csv
https://mekomsolutions.atlassian.net/browse/HSC-447
=> HSC-447: Fix copy text in Order Basket

configs/openmrs/frontend_assembly/spa-assemble-config.json
JIRA: https://mekomsolutions.atlassian.net/browse/HSC-417
=> HSC-417: Upgrade `esm-patient-medications-app`  to `v9.2.3-pre.7115`

configs/openmrs/frontend_assembly/spa-assemble-config.json
Ticket: https://mekomsolutions.atlassian.net/browse/HSC-450
=> HSC-450: Upgrade `esm-patient-billing-status-app` to `1.0.1-pre.27`.

configs/openmrs/initializer_config/patientidentifiertypes/facility_ids.csv
JIRA: https://mekomsolutions.atlassian.net/browse/LMP-6
=> Remove `Numéro Dossier` identifier from Patient registration form

pom.xml
JIRA: https://mekomsolutions.atlassian.net/browse/HSC-478
=> HSC-478: Update Ozone version to `1.0.0-alpha.13`

pom.xml
JIRA: https://mekomsolutions.atlassian.net/browse/HSC-478
=> HSC-478: Change ozone version to point to `1.0.0-alpha.13`

pom.xml
Issue: https://mekomsolutions.atlassian.net/browse/HSC-489
This PR adds the missing Odoo addons binaries
=> HSC-489: Add missing Odoo addons binaries

pom.xml
This PR updates `sale_order_price_recalculation` to version `10.0.1.0.1`
=> Update `sale_order_price_recalculation` to version `10.0.1.0.1`

README.md
Ticket: https://mekomsolutions.atlassian.net/browse/HSC-496
=> HSC-496: Add release notes for version 1.1.0
